In [1]:
from sklearn.model_selection import train_test_split, KFold
import numpy as np

In [3]:
x = np.arange(50).reshape(10,5)
y = np.zeros(10)
y[:5] = 1
print(x.shape)
print(y.shape)

(10, 5)
(10,)


In [5]:
train_X, test_X, train_Y, test_Y = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [7]:
train_X.shape

(7, 5)

In [11]:
kf = KFold(n_splits= 5)
i = 0
for train_index, test_index in kf.split(x):
    i+=1
    X_train, X_test = x[train_index], x[test_index]
    Y_train, Y_test = y[train_index], y[test_index]
    print("FOLD {}: ".format(i))
    print("X_test: ", X_test)
    print("Y_test: ", Y_test)
    print("-"*30)

FOLD 1: 
X_test:  [[0 1 2 3 4]
 [5 6 7 8 9]]
Y_test:  [1. 1.]
------------------------------
FOLD 2: 
X_test:  [[10 11 12 13 14]
 [15 16 17 18 19]]
Y_test:  [1. 1.]
------------------------------
FOLD 3: 
X_test:  [[20 21 22 23 24]
 [25 26 27 28 29]]
Y_test:  [1. 0.]
------------------------------
FOLD 4: 
X_test:  [[30 31 32 33 34]
 [35 36 37 38 39]]
Y_test:  [0. 0.]
------------------------------
FOLD 5: 
X_test:  [[40 41 42 43 44]
 [45 46 47 48 49]]
Y_test:  [0. 0.]
------------------------------
